-- Tabulky podle diagramu
CREATE TABLE Guests (
                        guest_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR2(100),
                        last_name VARCHAR2(100),
                        email VARCHAR2(100),
                        phone VARCHAR2(50),
                        id_card_number VARCHAR2(50),
                        date_of_birth DATE,
                        nationality VARCHAR2(50)
);

CREATE TABLE RoomTypes (
                           type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR2(100),
                           capacity NUMBER,
                           base_price NUMBER(10, 2)
);

CREATE TABLE Rooms (
                       room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       room_number VARCHAR2(20),
                       floor NUMBER,
                       type_id NUMBER REFERENCES RoomTypes(type_id)
);

CREATE TABLE Staff (
                       staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR2(100),
                       last_name VARCHAR2(100),
                       role VARCHAR2(50),
                       email VARCHAR2(100)
);

CREATE TABLE Services (
                          service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          service_name VARCHAR2(100),
                          price NUMBER(10, 2)
);

CREATE TABLE Reservations (
                              reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              guest_id NUMBER REFERENCES Guests(guest_id),
                              room_id NUMBER REFERENCES Rooms(room_id),
                              check_in TIMESTAMP,
                              check_out TIMESTAMP,
                              status VARCHAR2(50)
);

CREATE TABLE Invoices (
                          invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          reservation_id NUMBER REFERENCES Reservations(reservation_id),
                          total_amount NUMBER(10, 2),
                          issue_date TIMESTAMP
);

CREATE TABLE ServiceUsage (
                              usage_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              reservation_id NUMBER REFERENCES Reservations(reservation_id),
                              service_id NUMBER REFERENCES Services(service_id),
                              quantity NUMBER,
                              usage_date TIMESTAMP
);

-- ============================================================
--  checkOut  –  Odhlášení hosta (Oracle PL/SQL)
--  Uložená procedura volaná z aplikační vrstvy přes JDBC
-- ============================================================

CREATE OR REPLACE PROCEDURE GENERATE_INVOICE(
    p_res_id  IN  Reservations.reservation_id%TYPE,
    p_message OUT VARCHAR2          -- výstupní zpráva pro aplikační vrstvu
)
AS
    -- -------------------------------------------------------
    --  1. Lokální proměnné
    -- -------------------------------------------------------
    v_status      Reservations.status%TYPE;
    v_nights      NUMBER;
    v_final_bill  NUMBER(10, 2) := 0;
    v_invoice_id  Invoices.invoice_id%TYPE;

    -- Vlastní výjimky
    ex_not_found    EXCEPTION;
    ex_wrong_status EXCEPTION;
    ex_bad_dates    EXCEPTION;

BEGIN
    -- -------------------------------------------------------
    --  2. VALIDACE A NAČTENÍ ZÁKLADNÍCH DAT
    -- -------------------------------------------------------

    -- Načtení stavu a počtu nocí
BEGIN
SELECT status,
       TRUNC(check_out) - TRUNC(check_in) -- OPRAVA: Převedení na DATE a získání čistého čísla
INTO   v_status, v_nights
FROM   Reservations
WHERE  reservation_id = p_res_id;
EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE ex_not_found;
END;

    -- Kontrola 1: Aktivní pobyt?
    -- OPRAVENO
    IF v_status != 'CHECKED_IN' THEN
        RAISE ex_wrong_status;
END IF;

    -- Kontrola 2: Logika datumu
    IF v_nights <= 0 THEN
        RAISE ex_bad_dates;
END IF;

    -- -------------------------------------------------------
    --  3. VÝPOČET FINÁLNÍ ČÁSTKY
    -- -------------------------------------------------------

    -- OPRAVA: Použijeme už spočítanou proměnnou v_nights namísto složitého odečítání
SELECT (v_nights * rt.base_price)
           + NVL(SUM(s.price * su.quantity), 0)
INTO   v_final_bill
FROM   Reservations  r
           JOIN   Rooms         rm ON r.room_id      = rm.room_id
           JOIN   RoomTypes     rt ON rm.type_id     = rt.type_id
           LEFT JOIN ServiceUsage su ON r.reservation_id = su.reservation_id
           LEFT JOIN Services     s  ON su.service_id    = s.service_id
WHERE  r.reservation_id = p_res_id
GROUP BY rt.base_price; -- OPRAVA: Base_price musí být v GROUP BY, aby fungovala suma služeb

-- -------------------------------------------------------
--  4. DATABÁZOVÁ TRANSAKCE
-- -------------------------------------------------------

-- A) Změna stavu rezervace
UPDATE Reservations
SET    status = 'CHECKED_OUT'
WHERE  reservation_id = p_res_id;

-- B) Vytvoření faktury
INSERT INTO Invoices (reservation_id, total_amount, issue_date)
VALUES (p_res_id, v_final_bill, CURRENT_TIMESTAMP)
    RETURNING invoice_id INTO v_invoice_id;

-- C) Potvrzení transakce
COMMIT;

p_message := 'SUCCESS: Host odhlášen. Faktura ID = ' || v_invoice_id
                 || ', Částka = ' || v_final_bill || ' CZK';

-- -------------------------------------------------------
--  5. OŠETŘENÍ CHYB  →  ROLLBACK
-- -------------------------------------------------------
EXCEPTION
    WHEN ex_not_found THEN
        ROLLBACK;
        p_message := 'ERROR: Rezervace s ID ' || p_res_id || ' neexistuje.';

WHEN ex_wrong_status THEN
        ROLLBACK;
        p_message := 'ERROR: Lze odhlásit pouze hosty ve stavu Checked-in. Aktuální stav: ' || v_status;

WHEN ex_bad_dates THEN
        ROLLBACK;
        p_message := 'ERROR: Datum odjezdu musí být větší než datum příjezdu.';

WHEN OTHERS THEN
        ROLLBACK;
        p_message := 'CRITICAL ERROR: ' || SQLERRM;

END GENERATE_INVOICE;
/

-- Testovací data
INSERT INTO Guests (first_name, last_name, email, phone, id_card_number) VALUES ('Jan', 'Novák', 'jan@novak.cz', '123456789', 'OP12345');
INSERT INTO RoomTypes (name, capacity, base_price) VALUES ('Standard', 2, 1200);
INSERT INTO Rooms (room_number, floor, type_id) VALUES ('101', 1, 1);
INSERT INTO Reservations (guest_id, room_id, check_in, check_out, status) VALUES (1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + 2, 'ACTIVE');
COMMIT;